version: '3.8'
services: 
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    volumes: 
      - .:/app    

    depends_on: 
      - db

    
  
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_DATABASE: admin
      MYSQL_USER: sysdev
      MYSQL_PASSWORD: sys123*
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - .dbdata:/var/lib/mysql
    ports: 
      - 33066:3306